<a href="https://colab.research.google.com/github/Itz-Ayushi/Cognitive-Assignments/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ques 1


In [6]:
import numpy as np
arr=np.array([7,4,8,2,5])
print("original array:",arr)
print("adding 2:",arr+2)
print("multiplying 3",arr*3)
print("dividing 2:",arr/2)

original array: [7 4 8 2 5]
adding 2: [ 9  6 10  4  7]
multiplying 3 [21 12 24  6 15]
dividing 2: [3.5 2.  4.  1.  2.5]


Ques 2

In [7]:
 arr = np.array([1, 2, 3, 6, 4, 5])
 print("reversed array:",arr[::-1])

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
print("\nx:",x)
print("y:",y)
def most_frequent_value(arr):
  unique_values, counts = np.unique(arr, return_counts=True)
  index = np.argmax(counts)
  frequent_value = unique_values[index]
  indices = np.where(arr == frequent_value)[0]
  return frequent_value,indices
print("Most frequent value in x and its indices:", most_frequent_value(x))
print("Most frequent value in y and its indices:",most_frequent_value(y))


reversed array: [5 4 6 3 2 1]

x: [1 2 3 4 5 1 2 1 1 1]
y: [1 1 1 2 3 4 2 4 3 3]
Most frequent value in x and its indices: (1, array([0, 5, 7, 8, 9]))
Most frequent value in y and its indices: (1, array([0, 1, 2]))


Ques 3

In [10]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0][1])
print(arr[2][0])

20
70


Ques 4

In [25]:
ayushi = np.linspace(10,100,25)
print("Array:", ayushi)
print("Dimensions:", ayushi.ndim)
print("Shape:", ayushi.shape)
print("Total elements:", ayushi.size)
print("Data type:", ayushi.dtype)
print("Total bytes consumed:", ayushi.nbytes)

transposed = ayushi.reshape(25, 1)
print("\nTransposed Array using reshape():\n",transposed)
transpos_ed = ayushi.T
print("Transposed Array using T attribute:\n", transpos_ed)

print("\nTranspose using T attribute-\n")
reshaped_arr = ayushi.reshape(5,5)
print("Original Array:\n", reshaped_arr)
print("Transpose:\n", reshaped_arr.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200

Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transposed Array using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Transpose using T attribute-

Original Array:
 [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.

Ques 5

In [24]:
ucs420_ayushi= np.array([[10,20,30,40],
                  [50,60,70,80],
                  [90,15,20,35]])
print("Original array:\n",ucs420_ayushi)
print("\nMean:", np.mean(ucs420_ayushi))
print("Median:", np.median(ucs420_ayushi))
print("Unique:", np.unique(ucs420_ayushi))
print("Minimum:", np.min(ucs420_ayushi))
print("Maximum:", np.max(ucs420_ayushi))
print("Variance:", np.var(ucs420_ayushi))
print("Standard Deviation:", np.std(ucs420_ayushi))

reshaped_ucs420_ayushi = ucs420_ayushi.reshape(4,3)
print("\nReshaped array:\n", reshaped_ucs420_ayushi)

resized_ucs420_ayushi= np.resize(ucs420_ayushi,(2,3))
print("\nResized array:\n", resized_ucs420_ayushi)

Original array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Unique: [10 15 20 30 35 40 50 60 70 80 90]
Minimum: 10
Maximum: 90
Variance: 651.3888888888889
Standard Deviation: 25.522321385189258

Reshaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized array:
 [[10 20 30]
 [40 50 60]]
